kumuluzee:
  name: polnilne-postaje
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PolnilnePostaje
      connection-url: jdbc:postgresql://localhost:5432/projekt
      username: postgres
      password: postgres
  dev:
    scan-libraries:
      - entitete
      - storitve
  security:
    keycloak:
      json: '{
        "realm": "customers-realm",
        "bearer-only": true,
        "auth-server-url": "http://localhost:8082/auth/",
        "ssl-required": "external",
        "resource": "customers-api",
        "confidential-port": 0
      }'
integrations:
  zasedenost:
    base-url: http://localhost:8081/v1