apiVersion: apps/v1
kind: Deployment
metadata:
  name: zasedenost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zasedenost
  template:
    metadata:
      labels:
        app: zasedenost
    spec:
      containers:
        - image: xaodocker/projekt_zasedenost
          name: zasedenost
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: zasedenost
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: zasedenost